name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: integral-linker-435615-v7

      - name: Build Docker image
        run: |
          docker build -t gcr.io/integral-linker-435615-v7/backend .

      - name: Push Docker image
        run: |
          gcloud auth configure-docker
          docker push gcr.io/integral-linker-435615-v7/backend

      - name: Deploy to Cloud Run
        run: gcloud run deploy backend --image gcr.io/integral-linker-435615-v7/backend --region europe-west1 --platform managed --allow-unauthenticated --update-secrets /secrets/credentials.json=credentials-json:latest
