name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: integral-linker-435615-v7
          install_components: 'beta'  # Pour gcloud run

      - name: Configure Docker for gcloud
        run: |
          gcloud auth configure-docker

      - name: Build and push with Cloud Build
        run: |
          gcloud builds submit ./backend --tag gcr.io/integral-linker-435615-v7/backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend \
            --image gcr.io/integral-linker-435615-v7/backend \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated \
            --timeout=360s